=== nktrtmv/edm/edm-document-generator-gateway/src/Edm.DocumentGenerator.Gateway.Presentation/Authorization/DomainsRules/rules-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "DomainId": {
      "type": "string"
    },
    "Name": {
      "type": "string"
    },
    "RolesActions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ReadDocument": {
          "$ref": "#/$defs/Roles",
          "description": "Role ids with access to action. Will be combined with UpdateDocument roles"
        },
        "UpdateDocument": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateDocumentsClerks": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateDocumentsStatuses": {
          "$ref": "#/$defs/Roles"
        },
        "UploadCommentAttachmentToDocument": {
          "$ref": "#/$defs/Roles"
        },
        "CreateDocument": {
          "$ref": "#/$defs/Roles"
        },
        "ExportToExcel": {
          "$ref": "#/$defs/Roles"
        },
        "ReadTemplate": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateTemplate": {
          "$ref": "#/$defs/Roles"
        },
        "ExportPassesForms": {
          "$ref": "#/$defs/Roles"
        },
        "ExportPassesExcel": {
          "$ref": "#/$defs/Roles"
        },
        "ExportDocumentsSlas": {
          "$ref": "#/$defs/Roles"
        },
        "ReadDocumentNotificationTemplate": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateDocumentNotificationTemplate": {
          "$ref": "#/$defs/Roles"
        },
        "ReadDocumentCounter": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateDocumentCounter": {
          "$ref": "#/$defs/Roles"
        },
        "ReadReference": {
          "$ref": "#/$defs/Roles"
        },
        "UpdateReference": {
          "$ref": "#/$defs/Roles"
        }
      },
      "required": [
        "ReadDocument",
        "UpdateDocument",
        "UploadCommentAttachmentToDocument",
        "CreateDocument",
        "ExportToExcel",
        "ReadTemplate",
        "UpdateTemplate",
        "ReadDocumentNotificationTemplate",
        "UpdateDocumentNotificationTemplate",
        "ReadDocumentCounter",
        "UpdateDocumentCounter",
        "ReadReference",
        "UpdateReference"
      ]
    },
    "Reports": {
      "type": "object"
    },
    "Dashboards": {
      "type": "object"
    }
  },
  "required": [
    "DomainId",
    "Name",
    "RolesActions",
    "Reports",
    "Dashboards"
  ],
  "$defs": {
    "Roles": {
      "type": "array",
      "description": "Role ids with access to action",
      "items": {
        "type": "string",
        "pattern": "[a-zA-Z_-]+"
      }
    }
  }
}

=== nktrtmv/edm/edm-document-generator-gateway/src/Edm.DocumentGenerator.Gateway.Presentation/Authorization/DomainsRules/Contracts.json
{
  "$schema": "rules-schema.json",
  "DomainId": "8a3d776c-906a-4de2-9c20-1df638f1545b",
  "Name": "Договорная работа",
  "RolesActions": {
    "CreateDocument": [
      "commercial_initiator",
      "non_commercial_initiator",
      "intragroup_initiator",
      "investment_initiator"
    ],
    "ReadDocument": [
      "auditor"
    ],
    "UpdateDocument": [
      "commercial_initiator",
      "commercial_responsible_manager",
      "commercial_docflow_head",
      "commercial_docflow_employee",
      "commercial_authorized_signatory",
      "non_commercial_initiator",
      "non_commercial_responsible_manager",
      "non_commercial_docflow_employee",
      "non_commercial_docflow_head",
      "non_commercial_authorized_signatory",
      "non_commercial_accounting_specialist",
      "non_commercial_budget_controller",
      "intragroup_initiator",
      "intragroup_responsible_manager",
      "intragroup_docflow_employee",
      "intragroup_docflow_head",
      "intragroup_authorized_signatory",
      "intragroup_sighting",
      "investment_initiator",
      "investment_responsible_manager",
      "investment_docflow_employee",
      "investment_authorized_signatory"
    ],
    "UpdateDocumentsClerks": [
      "commercial_docflow_head",
      "intragroup_docflow_head",
      "investment_docflow_head",
      "non_commercial_docflow_head"
    ],
    "UploadCommentAttachmentToDocument": [
      "commercial_docflow_head",
      "intragroup_docflow_head",
      "investment_docflow_head",
      "non_commercial_docflow_head",
      "commercial_docflow_employee",
      "intragroup_docflow_employee",
      "investment_docflow_employee",
      "non_commercial_docflow_employee"
    ],
    "ExportToExcel": [
      "auditor",
      "commercial_docflow_head",
      "commercial_docflow_employee",
      "non_commercial_docflow_employee",
      "non_commercial_docflow_head",
      "intragroup_docflow_employee",
      "intragroup_docflow_head",
      "investment_docflow_employee",
      "investment_docflow_head",
      "commercial_initiator",
      "non_commercial_initiator"
    ],
    "ExportDocumentsSlas": [
      "auditor",
      "commercial_docflow_head",
      "commercial_docflow_employee",
      "non_commercial_docflow_employee",
      "non_commercial_docflow_head",
      "intragroup_docflow_employee",
      "intragroup_docflow_head",
      "investment_docflow_employee",
      "investment_docflow_head"
    ],
    "ReadTemplate": [
      "auditor"
    ],
    "UpdateTemplate": [],
    "ReadDocumentNotificationTemplate": [
      "auditor"
    ],
    "UpdateDocumentNotificationTemplate": [],
    "ReadDocumentCounter": [
      "auditor"
    ],
    "UpdateDocumentCounter": [],
    "ReadReference": [
      "auditor"
    ],
    "UpdateReference": []
  },
  "Reports": {
    "1": [
      "auditor",
      "report_view"
    ],
    "2": [
      "auditor",
      "report_view"
    ],
    "3": [
      "allow_all_no_access_check"
    ],
    "4": [
      "auditor",
      "report_view"
    ],
    "5": [
      "auditor",
      "report_view"
    ]
  },
  "Dashboards": {
    "10": [
      "auditor",
      "dashboard_view"
    ],
    "11": [
      "auditor",
      "dashboard_view"
    ],
    "20": [
      "auditor",
      "dashboard_view"
    ],
    "21": [
      "auditor",
      "dashboard_view"
    ],
    "30": [
      "allow_all_no_access_check"
    ],
    "31": [
      "allow_all_no_access_check"
    ],
    "32": [
      "allow_all_no_access_check"
    ],
    "40": [
      "auditor",
      "dashboard_view"
    ],
    "41": [
      "auditor",
      "dashboard_view"
    ],
    "50": [
      "auditor",
      "dashboard_view"
    ],
    "51": [
      "auditor",
      "dashboard_view"
    ],
    "60": [
      "auditor",
      "dashboard_view"
    ],
    "61": [
      "auditor",
      "dashboard_view"
    ]
  }
}
